### ISSUE TITLE
Crown Store Not Openning

### ISSUE THREAD

**Issue by HobbitForHire** [Lord-of-the-Craft/tracker#444]
Player graveyard_bones is unable to access the crown store. When selecting the option, the following page is blank. This happens in vanilla and modded. 
https://medal.tv/games/minecraft/clips/igleGRgIX9AVOasnL/d1337TMOjoqT?invite=cr-MSw0Z2ksNzk3Mzc0NTAs
https://medal.tv/games/minecraft/clips/igjonCDkXJe3s5-CU/d1337toVkdNN?invite=cr-MSxFUkosNzk3Mzc0NTAs

**Ticket refence number:**
RTS-159452

**Comment by Kowaman** [comment]
```
[23:53:58 WARN]: java.lang.NullPointerException: Cannot invoke "net.minegrid.module.crowns.CrownTransaction.isVoided()" because the return value of "net.minegrid.module.crowns.CrownPurchase$Record.getTransaction()" is null
[23:53:58 WARN]:        at net.minegrid.module.crowns.CrownProfile.lambda$getRecords$0(CrownProfile.java:57)
[23:53:58 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[23:53:58 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[23:53:58 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[23:53:58 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[23:53:58 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[23:53:58 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:53:58 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[23:53:58 WARN]:        at net.minegrid.module.crowns.CrownProfile.getRecords(CrownProfile.java:57)
[23:53:58 WARN]:        at net.minegrid.module.crowns.CrownProfile.getRecords(CrownProfile.java:61)
[23:53:58 WARN]:        at net.minegrid.module.crowns.CrownProfile.isPurchaseActive(CrownProfile.java:65)
[23:53:58 WARN]:        at net.minegrid.module.crowns.CrownMenuDaemon.lambda$crownPayments$16(CrownMenuDaemon.java:133)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreLocalView.lambda$runOpenEvents$0(CoreLocalView.java:61)
[23:53:58 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreLocalView.runOpenEvents(CoreLocalView.java:59)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreMenuSession.openDirectory(CoreMenuSession.java:332)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreMenuSession.openDirectory(CoreMenuSession.java:316)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreMenuSession.openDirectory(CoreMenuSession.java:306)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreMenuSession.openDirectory(CoreMenuSession.java:301)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.api.menu.active.Icon$Folder.lambda$setAction$0(Icon.java:235)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreIcon.lambda$runAction$1(CoreIcon.java:153)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.Foundation.trial(Foundation.java:670)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.Foundation.attempt(Foundation.java:665)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreIcon.lambda$runAction$2(CoreIcon.java:152)
[23:53:58 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.active.CoreIcon.runAction(CoreIcon.java:150)
[23:53:58 WARN]:        at Foundation.jar//net.minegrid.obelisk.core.menu.MenuEventHandler.onClick(MenuEventHandler.java:122)
[23:53:58 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[23:53:58 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:53:58 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:53:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[23:53:58 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2947)
[23:53:58 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[23:53:58 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[23:53:58 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[23:53:58 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:53:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:53:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1427)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[23:53:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1404)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1397)
[23:53:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1375)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1257)
[23:53:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[23:53:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Kowagirl** [comment]
One off issue due to broken transaction record (probably due to a crash), easy fix with an admin command. In future, please forward any tickets like this to Admin.
